

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: root
    password: rootpassword

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}
server:
  port: 8070

management:
  tracing:
    sampling:
      probability: 1.0


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  servers:
    - url: http://localhost:8000
      description: Kong API Gateway
