spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3309/payments_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redispass}

server:
  port: 8071

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.project.payment: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF

management:
  tracing:
    sampling:
      probability: 1.0


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  default-produces-media-type: application/json
  servers:
    - url: http://localhost:8000
      description: Kong API Gateway
